version: '3.8'

services:
  api:
    build: .
    container_name: "gdsc-ai-service-container"
    image: "gdscfptu/ai-service"
    ports:
      - "8000:80"
    volumes:
      - .:${HOME}/app
      - ${HOME}/app/env
    env_file:
      - ./.env